# @Microservices.Demo.Pricing.Service_HostAddress = http://localhost:5194
@Microservices.Demo.Pricing.Service_HostAddress = http://localhost:8082

POST {{Microservices.Demo.Pricing.Service_HostAddress}}/api/pricing/calculate-price
Accept: application/json
Content-Type: application/json
{
  "productCode": "TRI",
  "policyFrom": "2024-06-11T12:00:00Z",
  "policyTo": "2024-06-16T12:00:00Z",
  "selectedCovers": ["C1", "C2", "C3"],
  "answers": [
    {
      "questionCode": "NUM_OF_ADULTS",
      "questionType": "Numeric",
      "answer": 1
    },
    {
      "questionCode": "NUM_OF_CHILDREN",
      "questionType": "Numeric",
      "answer": 1
    },
    {
      "questionCode": "DESTINATION",
      "questionType": "Text",
      "answer": "EUR"
    }
  ]
}


###
