<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="elasticsearch\" />
    <Folder Include="kibana\" />
    <Folder Include="apm\" />
    <Folder Include="Logstash\conf.d\" />
  </ItemGroup>

</Project>
