input {
  tcp {
    port => 28081
    codec => json
  }
  http {
    port => 28080
    codec => json
  }
}

filter {
  if [Properties][Service] == "Products.Service" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-products-service" } }
  } else if [Properties][Service] == "Pricing.Service" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-pricing-service" } }
  } else if [Properties][Service] == "Policies.Service" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-policies-service" } }
  } else if [Properties][Service] == "Policies.Search.Service" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-policies-search-service" } }
  } else if [Properties][Service] == "Payments.Service" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-payments-service" } }
  } else if [Properties][Service] == "Gateway" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Properties][Environment]}-gateway" } }
  } else if [Service] == "Eureka.Server" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Environment]}-eureka-server" } }
  } else if [Service] == "Config.Server" {
    mutate { add_field => { "[@metadata][index]" => "log-%{[Environment]}-config-server" } }
  }
}

output {  
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "elastic"
    document_type => "log"
  }
}