spring.application.name=discovery-server
server.port=8761

eureka.client.register-with-eureka=false

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

management.metrics.enable.all=true
management.metrics.export.prometheus.enabled=true